# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://wzwtt.cf/blog
date_format: "ordinal"
title: 小章鱼的博客
subtitle: "小章鱼的博客"
description: ""
keywords: 小章鱼, 注水章鱼, 旧石塔
timezone: Asia/Shanghai
encoding: "utf-8"
# 页面左下角显示的年份
since: 1888
# 源码仓库，请替换成自己的
repository: wzwtt/blog
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: false
        hide-platforms: qq,facebook
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2022-08-13
    # My Popular Repositories
    side_bar_repo:
        enabled: false
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: false
        image_alt: 小章鱼
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: list
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Smart Octopus
organization: 旧石塔 Just
organization_url: 
github_username: wzwtt
location: 
email: 

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档
     
  -
    href: https://wzwtt.cf/
    label: 百宝箱

#   -
#     href: /open-source/
#     label: 开源

#  -
#    href: /wiki/
#    label: 维基

# -
#   href: /links/
#   label: 链接

# -
#    href: /about/
#    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar
comments_provider: beaudar
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# disqus 配置参考：https://disqus.com
disqus:
    username: 
# gitment 配置参考：https://imsun.net/posts/gitment-introduction/
gitment:
    owner: 
    repo: 
    oauth:
        client_id: 
        client_secret: 
# gitalk 配置参考：https://github.com/gitalk/gitalk#install
gitalk:
    owner: 
    repo: 
    clientID: 
    clientSecret: 
# utterances 配置参考：https://utteranc.es/
utterances:
    repo: wzwtt/blog
# beaudar 配置参考：https://beaudar.lipk.org/
beaudar:
    repo: wzwtt/blog
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: G-GBV2WSZ3JX
    adsense:
        footer: false
        sidebar: false
        sidebar-detail: false
        content_header: false
        content_footer: false
